version: '3'

services:
  app:
    build: ./.docker
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/apache/app.conf:/etc/apache2/sites-enabled/app.conf
      - ./app/logs/:/var/log/apache2

  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: test_db
